name: Advent of Code 2023 

on: [push]

jobs:
  run-challenges:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2


    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.11'


    - name: Run Challenges and edit markdown
      run: python timer.py


    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1
      with:
        default_author: github_actions
        message: 'Added benchmark'
        add: 'README.md'
